name: Update examples/weirdness Branch
on:
  push:
    branches:
      - "main"
    paths:
      - "examples/weirdness/**"
      - ".github/workflows/examples-weirdness.yml"
permissions:
  contents: write
jobs:
  deploy:
    name: Update examples/weirdness Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: examples/weirdness
          FOLDER: examples/weirdness
          SQUASH_HISTORY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
